### ISSUE TITLE
consistent use of "Since..."

### ISSUE THREAD

**Issue by mgylling** [openbadges/openbadges-specification#106]
In the 1.1 spec, new features were decorated with the "Since 1.1" moniker. It appears this was not done for 2.0 (compare eg [Extensions](http://openbadgespec.org/#Extensions) with [Endorsements](http://openbadgespec.org/#Endorsement)).

For future versions of the spec, decide whether to a)drop this moniker entirely and use a dedicated "changes since previous version" section instead, or b) to continue to use it, but consistently.

**Comment by ottonomy** [comment]
"Since 1.1" is used for extension and extension validation sections of the spec. "Since 2.0" was not implemented with the currently-published BA recommendation, but it could apply to a number of new features, such as the Criteria, Image, CryptographicKey, Endorsement, and Evidence classes.

The [1.1 history page](http://openbadgespec.org/history/1.1.html) has a little information about each of the features marked with "Since 1.1" on the front page and a couple other additions, like the `@context`, `type`, and `id` properties that are not marked with a "since 1.1" in the doc. 

I commented on #113 that I think consistency, usefulness, efficiency would be how I would order priorities when we decide how to use "since". 

I lean toward removing the "since 1.1" markers and beefing up the history & errata sections (see #113) instead.

**Comment by mgylling** [comment]
Fixed by #122
