### ISSUE TITLE
Is Assertion.image potentially self-referencing?

### ISSUE THREAD

**Issue by mgylling** [openbadges/openbadges-specification#109]
If the Assertion being read comes from a baked badge, then does Assertion.image potentially contain the same IRI as Assertion.id, and if so what purpose does it serve? 

Maybe I am misreading, and even if not, not sure this warrants a clarification in the spec, but I stumbled upon it so thought I'd ask.

**Comment by ottonomy** [comment]
Assertion image is a URL to a baked image. The BadgeClass image is a URL or a dataURI to a unbaked image representing the achievement. 

Here are the current descriptions, and for most users these have been clear, but we have had some implementers historically confusing the two and putting a URL to the same unbaked image in both places.

Assertion.image:
> IRI or document representing an image representing this user’s achievement. This must be a PNG or SVG image, and should be prepared via the Baking specification. An ‘unbaked’ image for the badge is defined in the BadgeClass and should not be duplicated here.

BadgeClass.image:
> IRI of an image representing the achievement. May be a Data URI, or URI where the image may be found.

**Comment by ottonomy** [comment]
Updating once more to say more clearly that these IDs are not the same.

The Assertion.image property, as implemented across the ecosystem, is an optional property that points to the download location of an image file. No guidelines were given to verifiers and similar services about how to make a request for that URI like they are for requesting the core JSON-LD objects (which specify what should be used for Accept headers and open the possibility of content negotiation").

It is conceivable that an implementing issuer could make the baked image available at the Assertion.id if the client specifically requests an image format. However, I think using that id for the Assertion.image property would be dangerous. At that ID, JSON-LD content must be served by default if no Accept header is provided, and as far as I can tell, my browsers are not sending any Accept header when making requests for images included in webpages with `<img src="...">` tags. If the optional Assertion.image property is used, it should point to a different URI than Assertion.id because of those special rules that Assertion.id must follow for hosted assertions. The good news is, no implementer has tried to do this.

I think no change is necessary here, but as I wrote most of the text in question, if it is confusing to other stakeholders, it should be clarified.

**Comment by mgylling** [comment]
On the 2016-02-09 WG call, it was agreed to close this issue without making any changes to the spec.
