### ISSUE TITLE
add link to errata page

### ISSUE THREAD

**Issue by mgylling** [openbadges/openbadges-specification#113]
For the live version of the 2.0 spec at openbadgespec.org, add link at the top of the doc to a new errata page, where we list errata and/or in-place edits done since the original publishing at Jan 1 2017. 

A label has been created for issues that are going down the in-place edit route.

**Comment by ottonomy** [comment]
I suggest that this page could be added as history/2.0 which could describe the updates between 1.1 and 2.0 and then have an errata section for changes pushed since the initial "2.0" release.

**Comment by mgylling** [comment]
Good idea. And that could also mean we could remove the "Since 1.1" (#106) markers right? Assuming the doc also includes a list of 1.0-->1.1 features.

**Comment by ottonomy** [comment]
@mgylling I think the priorities about how to use "Since.." markers (#106) should be about:

1. Consistency across the docs
2. Providing essential information to readers
3. Efficiency (not providing the same information multiple times needlessly)

If the markers are essential, then they should be applied consistently throughout the main doc, but if not, then we should fall back to 3 and limit them to the history pages, which most people don't read. From my informal conversations with people reading this page 90%+ want to know only about how to implement the current version and don't care about history.

**Comment by timothyfcook** [comment]
From Working Group: Proposal to add this to the existing History section on openbadgespec.org

**Comment by mgylling** [comment]
Fixed by #122
