### ISSUE TITLE
add standard IMS frontmatter & styles

### ISSUE THREAD

**Issue by mgylling** [openbadges/openbadges-specification#114]
Add the standard IMS frontmatter and styles to the base document, as e.g. in [QTI 2.2](https://www.imsglobal.org/question/qtiv2p2/imsqti_v2p2_impl.html).

Coordinate with Mark McKell, who is in charge of formatting etc in IMS.

**Comment by ottonomy** [comment]
👍 

Also, I think we should understand before March how this document will be situated within its final publishing location at IMSglobal.org. We can set up this document to generate HTML in the desired format instead of in the openbadgespec.org format? We should also know what the relative URLs are, as we'll want to keep intact the links between spec and examples.

Am I right in assuming we'll need to implement that before publication of the "working draft" milestone March 1?

**Comment by mgylling** [comment]
Yes, you are right that all these things need to be settled. I am working with Mark McKell, and hope to have all answers by next weeks call.

**Comment by mgylling** [comment]
Done in #123. Some further tweaks and improvements will follow later.
