### ISSUE TITLE
IdentityObject - email upper/lower case issue

### ISSUE THREAD

**Issue by navreme** [openbadges/openbadges-specification#2]
There is a real problem with the case of letters in e-mails to be hashed.

It is allowed to use both Upper and Lower cases in email "local part" (see e.g. wkpd with links to RFC standards: http://en.wikipedia.org/wiki/Email_address#Local_part ); however, all these forms are treated equaly as the same identity:

john.doe@mail.com (version1) == John.Doe@mail.com (version2)

However, using hashIdentity, different outputs appears and e.g. Mozilla Backpack can not solve this similarity (or even matching other formats like JOHN.doe@ with john.DOE@ etc.).

Needs urgent standard update and (maybe also) update the Mozz code to try also uppercase version of e-mail (et least one more try for quite common version2 above).

**Comment by ottonomy** [comment]
This remains a problem, but I think the implementation solution (at least for the Backpack) would be to allow users to authenticate/verify multiple casings of their email address within the Backpack, so that they can accept badges no matter what case issuers deliver badges to them in. I don't think much can be done at the specification level here, so I'm going to close this issue. Further discussion is welcomed, and if anyone thinks this is the appropriate venue for it, feel free to reopen or refile this issue.
