### ISSUE TITLE
BadgeAssertion == AchievementCredential

### ISSUE THREAD

**Issue by elf-pavlik** [openbadges/openbadges-specification#32]
Hi @ottonomy 

Looking at:
http://specification.openbadges.org/credentials/#DefinedAchievementAssertion

IMO BadgeAsserion pretty much serves as AchievementCredential, I tried to remove some of the nesting but we still need to look how to merge values of *assertion*
https://gist.github.com/elf-pavlik/029917ccc535e889f693/7c6430cc6e45c74bb6ff17d58683db8124709c0f

**Comment by elf-pavlik** [comment]
I think I got pretty close in this revision
https://gist.github.com/elf-pavlik/029917ccc535e889f693/abb0de12f0a31eac4e679a229fb0413d5c5ab20e

**Comment by ottonomy** [comment]
Thanks, @elf-pavlik 

Seeing the line `"achievement": ["https://bigunivertsity.edu/credentials/BA"]` warms my heart -- that's what I would like to be able to ask about an identity: "What badges/achievements have been earned by this individual (that I am privileged to have shared with me)?"

One reason for the messy nesting-heavy structure from [your first gist](https://gist.github.com/elf-pavlik/029917ccc535e889f693/a94253fcf366e633738ae8635e9c38154d59d57a) is that the format shown there has some legacy weight from the pre-linked data 1.0 version of Open Badges that this format is backwards compatible with.

For the next breaking-change version, I would probably like to see Assertions congruent with Identity Credentials, as long as there is alignment on the recipient identifier (the badges philosophy is to allow badges to be issued to the identifier you know somebody by, rather than requiring it to be a particular Identity Document URL. There has been some interesting conversation around identifiers in the Credentials mailing list over the last week, so I expect to see some creative solutions in the coming year.

However, since Open Badges 1.1 is about ready to be released (and because the many 1.0 badges may be automatically translated to 1.1 by adding id, type and context), I also hope that if the Identity Credentials spec and the Credentials Vocabulary starts getting used before Open Badges hits 2.0 that the existing 1.1 linked data Open Badges will be able to be represented within an Identity Document too.

**Comment by elf-pavlik** [comment]
@ottonomy I took this example from draft document with title **Credentials Vocabulary**, I understand that we should keep in mind pre Linked Data open bages (*legacy*). IMO designing new vocabulary directly around it, doesn't put us in best position. I would prefer considering that Open Badges 2.0 use Web Credentials but 1.x have some compatibility layer/adapter which doesn't limit design of Web Credentials. Let's discuss it during telecon?

**Comment by ottonomy** [comment]
:+1:

**Comment by elf-pavlik** [comment]
I just made another revision which draws clearer distinction between Credential and Achievement. Also removing *Issuer* type/class since we use *issuer* property, instead I added http://schema.org/EducationalOrganization just as we use http://schema.org/Person already (and not *Earner*)

**Comment by ottonomy** [comment]
Going to close this, as the Credentials Community group is moving on to different directions. Looking forward to future investigations of compatibility between Open Badges and Open Credentials, as that spec morphs and moves toward becoming a reality. Hope you are well, @elf-pavlik! Cheers!
