### ISSUE TITLE
Link profiles across multiple platforms

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#83]
Badge Issuers may use multiple badge issuing platforms or wish to transition from one to another.

**User Stories**: 
1. As an issuer, I want to have all of my issued badges reference a single issuer profile  so that I may use multiple badge-issuing applications or switch between platforms.
2. As a consumer or recipient, I want to understand when multiple Badge Assertions are awarded by the same organization or individual, even if that issuer uses multiple platforms.

**Comment by 1l2p** [comment]
I am not sure I fully understand what is being proposed here, but as much as possible issuer identity should be independent of issuer platform. However, aggregating badges that were issued by the same institution, with different institutional identities, seems to best be handled in the backpack/wallet rather than the badge itself.

**Comment by ottonomy** [comment]
How about:
`"sameAs": "https://other.net/profile/3"`? 

If that appears claimed in an endorsement you trust, you can associate them. Or if two profiles have a property verified by endorsements ypu trust, you can associate them. 

For 1, just point the `issuer` property in a BadgeClass or Assertion to the same profile? Of course, you'll have to prove that it's ok that you made that claim. The second issuing platform and the eventual consumer of the badge will have to trust that the same entity triggered the publication. That's the root problem to solve (number 2). The "same domain" assumption you're otherwise relying on is far weaker than you would like. 

Fully agree with @1l2p. The identity provider should be a wallet or wallet service that handles authenticating identity. Authenitcating *identifiers* is a different function and orthogonal problem.

**Comment by ottonomy** [comment]
With #88, this is made possible via Endorsement in the 2.0 Recommendation.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
