### ISSUE TITLE
Define Metadata related to the Badge Image

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#85]
Some metadata about the badge image could help it be more easily displayed.
### User Stories:
1. As a badge issuer I want to define metadata related to my badge image so that the image can be more machine-readable, richly displayed and understood in a number of contexts and accessibility situations.
2. As a sight-impaired consumer of badges, I want to access a description of badge images that I encounter so that I can understand those badges.

**Comment by ottonomy** [comment]
Example metadata:
- dimensions
- @2x high-resolution version
- animatedGifVersion amirite!?
- title
- description

**Comment by ottonomy** [comment]
We've had a request to allow attribution of authors of works used in the badge image, such as creative commons licensed illustrations.

**Comment by ottonomy** [comment]
See also https://schema.org/ImageObject

**Comment by ottonomy** [comment]
I'm initially proposing just `id`, `caption`, and `author`. Caption alone sohuld be able to serve all the listed use cases.

I was considering adding `height` and `width`, but the schema.org ImageObject (MediaObject) that I am basing this on uses a complex vocab for declaring that information instead of just a simple Number value. `"height": {"value": 400, "unitCode": "E37"}` means 400 pixels. With CSS being so good these days, I don't think we need this info in the metadata to serve our needs. People are free to add it if they want, so we could see if the market demands it.

**Comment by jbohrer** [comment]
I support this approach (id, caption, author) and agree that height and width seem redundant at this point.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
