### ISSUE TITLE
Revoke a Badge Assertion

### ISSUE THREAD

**Issue by timothyfcook** [openbadges/openbadges-specification#87]
### User Story:

As a badge issuer, I want to revoke a badge Assertion I have previously issued, so that consumers do not think it is still valid.

**Comment by kayaelle** [comment]
Should list the specific use cases for this. Since with existing "infrastructure" there's no actual "claiming of a badge" and no way for an issuer to know if a badge has been consumed or not. Signed badges provide the revoke list but if that list gets lost, it's unclear whether the badge was revoked. For hosting badges, there's no way to distinguish between a revoked badge or when that is no longer being hosted.

**Comment by ottonomy** [comment]
Thanks, @kayaelle. One point to note is that #80 contains a use case for badge consumers to verify revocation status of a badge that is related to this issue, but probably shouldn't be duplicated here:

> As a badge consumer, I want to verify that an Assertion has not been revoked by its issuer, so that I can trust its claims about the recipient remain valid.

I think this division of issues is fine, but open to merging them if necessary. Put the consumer stories there, and the issuer stories here.

We could consider this issue as separate stories for hosted and signed assertions:

* As a badge Issuer, I want to revoke a signed Assertion and ensure consumers will be able to verify the badge is revoked, so that I can ensure consumers do not accord trust in a recipient when it is no longer applicable.
* As a badge issuer, I want to revoke an assertion that relied on hosted verification.

-- 

On implementation,

Some implementation details from v1.x around the verification information are worth revisiting. 

For instance:

* The `uid` field in the Assertion makes little sense for hosted assertion when there is an `@id` field. It is currently used for signed assertions to determine verification with a revocationList. In the Linked Data model, `@id`s are the property used to provide canonical identifiers for subjects, but it needs to be
* The `verify.url` field makes no sense either for hosted verification when there is an `@id`. It makes no sense for a signed verification, because the key should be referenced from the Issuer Profile instead of the Assertion (see #89).


It may be very interesting to do something like add a revocationInfo property to the Assertion class to enable multiple different methods of checking for revocation of signed and/or hosted badges other than revocationLists. This could include posting revocation info to centralized services, or decentralized databases like blockchains.

**Comment by ottonomy** [comment]
It may be interesting to look at the use cases for this at the point of issue of the revocable badge as opposed to at the point of revocation. For your consideration, suppose we add these to the above user stories:

1. As a badge issuer, I would like to specify an HTTP url where a consumer may get an up-to-date representation of a badge including its revocation status (the traditional `hosted` verification method)
2. As a badge issuer, I would like to specify a `revocationList` for all badges I award where users may find `@id`s of revoked badges I have awarded (the traditional revocation method for `signed`-verification Assertions).
3. As a badge issuer, I would like to specify an additional service where revocation information for individual signed badges may be obtained for consumers who understand the method. (essentially enabling revocation/verification extensions for badges)

The third one here could enable future methods to bring into the spec, perhaps blockchain or distributed peer-to-peer methods of storing revocation information that have not yet gotten to official specification level.

**Comment by mgylling** [comment]
Closing this issue, as it was resolved by the 2.0 Recommendation. This issue and all other issues resolved by 2.0 can be found via the 2.0 Release Candidate milestone and PR #99.
